name: Example Flask CI

on:
  push:
    branches: ['main']
  pull_request:
    types: [opened, synchronize]
    branches: ['main']

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: w-duffy/group-project-action@v1.0.0
